In [2]:
#Copies and Views
import numpy as np

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b = a

In [5]:
b is a

True

In [6]:
b.shape = 3,4

In [7]:
a.shape

(3, 4)

In [8]:
b.shape

(3, 4)

In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
def f(x):
    print(id(x))
    
id(a) # id is a unique identifier of an object    

2099231764688

In [16]:
f(a)

2099231764688


In [17]:
c = a.view()

In [18]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
c is a

False

In [21]:
c.base is a # c adalah tampilan data yang dimiliki a

True

In [22]:
c.flags.owndata

False

In [23]:
c.shape = 2,6

In [24]:
a.shape

(3, 4)

In [25]:
c[0,4] = 1234 #data a berubah

In [26]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [27]:
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [28]:
a[1,1] = 100 #data c berubah
a

array([[   0,    1,    2,    3],
       [1234,  100,    6,    7],
       [   8,    9,   10,   11]])

In [29]:
c

array([[   0,    1,    2,    3, 1234,  100],
       [   6,    7,    8,    9,   10,   11]])

In [30]:
#scalling
s=a[:, 1:3]

In [31]:
s

array([[  1,   2],
       [100,   6],
       [  9,  10]])

In [32]:
s[:] = 50

In [33]:
s

array([[50, 50],
       [50, 50],
       [50, 50]])

In [34]:
a

array([[   0,   50,   50,    3],
       [1234,   50,   50,    7],
       [   8,   50,   50,   11]])

In [35]:
#deep copy

d = a.copy()
d

array([[   0,   50,   50,    3],
       [1234,   50,   50,    7],
       [   8,   50,   50,   11]])

In [36]:
d is a

False

In [37]:
d.base is a     # d doesn't share anything with a

False

In [38]:
d[0,0] = 999
d

array([[ 999,   50,   50,    3],
       [1234,   50,   50,    7],
       [   8,   50,   50,   11]])

In [39]:
a

array([[   0,   50,   50,    3],
       [1234,   50,   50,    7],
       [   8,   50,   50,   11]])

In [40]:
a = np.arange(int(1e8))
a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [41]:
b = a[:100].copy()

In [42]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [43]:
del a

In [44]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])