In [11]:
import numpy as np
from numpy import pi

In [12]:
a1 = np.ones((2,3), dtype=int)
b1 = np.random.random((2,3))
a1

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
a1 *=3

In [14]:
a1

array([[3, 3, 3],
       [3, 3, 3]])

In [15]:
b1

array([[0.89313735, 0.0185415 , 0.20719593],
       [0.72767428, 0.38135242, 0.62990149]])

In [16]:
b1 += a1

In [17]:
b1

array([[3.89313735, 3.0185415 , 3.20719593],
       [3.72767428, 3.38135242, 3.62990149]])

In [25]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b

array([0.        , 1.57079633, 3.14159265])

In [26]:
b.dtype.name

'float64'

In [27]:
a

array([1, 1, 1])

In [28]:
c = a+b

In [29]:
c

array([1.        , 2.57079633, 4.14159265])

In [30]:
c.dtype.name

'float64'

In [37]:
d1 = np.exp(c*1j)

In [38]:
d1

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [39]:
d1.dtype.name

'complex128'

In [40]:
a = np.random.random((2,3))
a

array([[0.9312978 , 0.91919941, 0.39398396],
       [0.28952313, 0.91490605, 0.47297129]])

In [41]:
a.sum()

3.921881639447255

In [42]:
a.min()

0.2895231273037656

In [43]:
a.max()

0.9312978040409243

In [44]:
b = np.arange(12).reshape(3,4)

In [45]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [47]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [48]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)