In [4]:
#Fancy indexing and index tricks
import numpy as np

a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [5]:
i = np.array([1,1,2,4,6])
i

array([1, 1, 2, 4, 6])

In [6]:
a[i]

array([ 1,  1,  4, 16, 36], dtype=int32)

In [7]:
j = np.array( [ [5, 8], [4, 9] ])
j

array([[5, 8],
       [4, 9]])

In [8]:
a[j]

array([[25, 64],
       [16, 81]], dtype=int32)

In [9]:
palette = np.array ([ [ 0,0,0],     #black
                     [255,0,0],    #red
                     [0,255,0],    #green
                     [0,0,255],    #blue
                     [255,255,255] #putih
                    ])
image = np.array([ [0,1,2,0], 
                   [0,3,4,0] ])
palette

array([[  0,   0,   0],
       [255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255],
       [255, 255, 255]])

In [10]:
image = np.array( [ [0,1,2,0], [0,3,4,0] ])

In [11]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [12]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
i = np.array( [ [0,1], [1,2] ])
j = np.array( [ [2,1], [3,3] ])
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [14]:
i

array([[0, 1],
       [1, 2]])

In [15]:
j

array([[2, 1],
       [3, 3]])

In [16]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [17]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [18]:
l = [i,j]
a[l]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


array([[ 2,  5],
       [ 7, 11]])

In [19]:
s = np.array([i,j])

In [20]:
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [21]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [22]:
time = np.linspace(20, 145, 5)
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [23]:
data = np.sin(np.arange(20)).reshape(5,4)
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [27]:
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1], dtype=int64)

In [28]:
time_max = time[ind]
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [58]:
data_max = data[ind, range(data.shape[1])] # => data[ind[0],0], data[ind[1],1]...
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [63]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [64]:
a[[0,0,2]] = [1,2,3]
a

array([2, 1, 3, 3, 4])

In [65]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [66]:
a[[0,0,2]]+=1
a

array([1, 1, 3, 3, 4])

In [67]:
#Indexing with Boolean Arrays

a = np.arange(12).reshape(3,4)
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [69]:
a[b] = 0

In [70]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [80]:
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,True])
b2 = np.array([True,False,True,False])

a[b1,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a[:,b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [83]:
a[b1,b2]

array([ 4, 10])

In [92]:
a = np.array([2,3,4,5])
b = np.array([8,2,5])
c = np.array([5,4,6,8,3])
ax,bx,cx = np.ix_(a,b,c) #fungsi ix untuk menghitung ax+bx*cx

In [93]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [94]:
bx

array([[[8],
        [2],
        [5]]])

In [95]:
cx

array([[[5, 4, 6, 8, 3]]])

In [96]:
ax.shape , bx.shape , cx.shape

((4, 1, 1), (1, 3, 1), (1, 1, 5))

In [97]:
result = ax+bx*cx

In [98]:
result

array([[[42, 34, 50, 66, 26],
        [12, 10, 14, 18,  8],
        [27, 22, 32, 42, 17]],

       [[43, 35, 51, 67, 27],
        [13, 11, 15, 19,  9],
        [28, 23, 33, 43, 18]],

       [[44, 36, 52, 68, 28],
        [14, 12, 16, 20, 10],
        [29, 24, 34, 44, 19]],

       [[45, 37, 53, 69, 29],
        [15, 13, 17, 21, 11],
        [30, 25, 35, 45, 20]]])

In [115]:
result[3,2,2]

35

In [116]:
a[3]+b[2]*c[2]

35

In [120]:
def ufunc_reduce(ufct, *vectors):
    vs = np.ix_(*vectors)
    r = ufct.identity
    
    for v in vs:
        r = ufct(r,v)
    
    return r

In [122]:
ufunc_reduce(np.add , a, b, c)

array([[[15, 14, 16, 18, 13],
        [ 9,  8, 10, 12,  7],
        [12, 11, 13, 15, 10]],

       [[16, 15, 17, 19, 14],
        [10,  9, 11, 13,  8],
        [13, 12, 14, 16, 11]],

       [[17, 16, 18, 20, 15],
        [11, 10, 12, 14,  9],
        [14, 13, 15, 17, 12]],

       [[18, 17, 19, 21, 16],
        [12, 11, 13, 15, 10],
        [15, 14, 16, 18, 13]]])

In [125]:
a[0]+b[0]+c[0]

15