In [2]:
import numpy as np

#One-dimensional
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
a[2]

8

In [4]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [5]:
a[ : :-1]                                 # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [12]:
for i in a:
    print(round(i**(1/3.)))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [10]:
10**(1/2.)

3.1622776601683795

In [27]:
#Multidimensional
def f(x,y):
    return 10*x+y
    

b = np.fromfunction(f,(4,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [28]:
 b[2,3] #baris ke-2 kolom ke-3 mulai dari nol

23

In [29]:
b[0:5, 1] #kolom satu semua baris

array([ 1, 11, 21, 31])

In [30]:
b[ : ,1] 

array([ 1, 11, 21, 31])

In [31]:
b[1:3, : ] 

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [32]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([30, 31, 32, 33])

In [33]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
...                 [ 10, 12, 13]],
...                [[100,101,102],
...                 [110,112,113]]])

In [34]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [35]:
c.shape

(2, 2, 3)

In [36]:
c.ndim

3

In [37]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [38]:
c[0,...]                                   # same as c[0,:,:] or c[0]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [39]:
c[0]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [40]:
c[...,2]    # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [41]:
for row in b:
...     print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]


In [42]:
for element in b.flat:
...     print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
