In [30]:
#Shape Manipulation
import numpy as np

a= np.floor(10*np.random.random((3,4)))
a

array([[8., 9., 1., 4.],
       [9., 0., 3., 3.],
       [2., 1., 2., 9.]])

In [31]:
a.shape

(3, 4)

In [32]:
a.ravel() #menjadi flat vector -- return

array([8., 9., 1., 4., 9., 0., 3., 3., 2., 1., 2., 9.])

In [33]:
a.T #transpose matriks baris jadi kolom, kolom jadi baris -- return

array([[8., 9., 2.],
       [9., 0., 1.],
       [1., 3., 2.],
       [4., 3., 9.]])

In [34]:
a.T.shape

(4, 3)

In [35]:
a.shape

(3, 4)

In [36]:
a.reshape(6,2) #mengubah ukuran matriks -- return

array([[8., 9.],
       [1., 4.],
       [9., 0.],
       [3., 3.],
       [2., 1.],
       [2., 9.]])

In [37]:
a.shape

(3, 4)

In [38]:
a.resize(6,2) #mengubah ukuran matriks -- no return

In [39]:
a

array([[8., 9.],
       [1., 4.],
       [9., 0.],
       [3., 3.],
       [2., 1.],
       [2., 9.]])

In [44]:
a.shape

(6, 2)

In [50]:
a.reshape(3,-1)

array([[8., 9., 1., 4.],
       [9., 0., 3., 3.],
       [2., 1., 2., 9.]])