In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('patientData.csv')

In [3]:
dataset

Gender   Age  Albumin Liver Disease
0  Female  62.0      3.3           Yes
1  Female  65.0      3.2           Yes
2  Female  45.0      3.1            No
3    Male  40.0      4.1            No
4    Male  50.0      NaN           Yes
5  Female  55.0      3.3            No
6    Male   NaN      3.6           Yes
7    Male  67.0      3.8           Yes
8    Male  75.0      3.0            No
9  Female  64.0      3.4           Yes

In [4]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, 3].values

In [5]:
X

array([['Female', 62.0, 3.3],
       ['Female', 65.0, 3.2],
       ['Female', 45.0, 3.1],
       ['Male', 40.0, 4.1],
       ['Male', 50.0, nan],
       ['Female', 55.0, 3.3],
       ['Male', nan, 3.6],
       ['Male', 67.0, 3.8],
       ['Male', 75.0, 3.0],
       ['Female', 64.0, 3.4]], dtype=object)

In [6]:
Y

array(['Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes'],
      dtype=object)

In [7]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [8]:
X

array([['Female', 62.0, 3.3],
       ['Female', 65.0, 3.2],
       ['Female', 45.0, 3.1],
       ['Male', 40.0, 4.1],
       ['Male', 50.0, 3.422222222222222],
       ['Female', 55.0, 3.3],
       ['Male', 58.111111111111114, 3.6],
       ['Male', 67.0, 3.8],
       ['Male', 75.0, 3.0],
       ['Female', 64.0, 3.4]], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
Y

array([1, 1, 0, 0, 1, 0, 1, 1, 0, 1])

In [11]:

# Split the data between the Training Data and Test Data

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2
                                                    ,random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [13]:
X_train

array([[-1.        ,  1.        , -0.89871681, -0.32793138],
       [ 1.        , -1.        ,  0.74838599, -0.40624335],
       [ 1.        , -1.        ,  0.86603619, -1.11105109],
       [-1.        ,  1.        ,  0.05555704,  0.29856439],
       [-1.        ,  1.        ,  1.10133659,  1.00337213],
       [-1.        ,  1.        , -2.07521881,  2.06058373],
       [ 1.        , -1.        ,  0.51308559, -0.75864722],
       [ 1.        , -1.        , -0.31046581, -0.75864722]])

In [14]:
X_test

array([[ 1.        , -1.        , -1.48696781, -1.46345495],
       [-1.        ,  1.        ,  2.04253819, -1.81585882]])